<?php
/**
 * Plugin Name: OMOS Core Tools
 * Plugin URI: https://omos.onegodian.com/
 * Description: WordPress bridge for OMOS runtime health, manifest sync, Ask OMOS, Council, tools and node heartbeat.
 * Version: 1.4.0
 * Author: Gregory Lamar Jones / ONEGODIAN, LLC
 */
if (!defined('ABSPATH')) exit;
final class OMOS_Core_Tools {
 const VERSION='1.4.0'; const OPT='omos_core_tools_settings'; const CACHE='omos_manifest_v140';
 function __construct(){
  add_action('admin_menu',[$this,'menu']); add_action('admin_init',[$this,'settings']); add_action('rest_api_init',[$this,'rest']); add_action('omos_hourly_heartbeat',[$this,'heartbeat']);
  foreach(['omos_runtime_status'=>'sc_status','omos_manifest'=>'sc_manifest','omos_ask'=>'sc_ask','omos_council'=>'sc_council','omos_tool_grid'=>'sc_tools','omos_docs_grid'=>'sc_docs','omos_decision_history'=>'sc_history','omos_belief_mapper'=>'sc_belief','omos_unity_dashboard'=>'sc_dashboard'] as $t=>$m)add_shortcode($t,[$this,$m]);
 }
 static function activate(){if(!wp_next_scheduled('omos_hourly_heartbeat'))wp_schedule_event(time()+60,'hourly','omos_hourly_heartbeat');if(!get_option(self::OPT))add_option(self::OPT,['runtime_url'=>'https://omos.onegodian.com','api_key'=>'','cache_minutes'=>5,'node_name'=>get_bloginfo('name'),'node_type'=>'wordpress']);}
 static function deactivate(){wp_clear_scheduled_hook('omos_hourly_heartbeat');}
 private function cfg(){return wp_parse_args(get_option(self::OPT,[]),['runtime_url'=>'https://omos.onegodian.com','api_key'=>'','cache_minutes'=>5,'node_name'=>get_bloginfo('name'),'node_type'=>'wordpress']);}
 private function url($p=''){return untrailingslashit($this->cfg()['runtime_url']).'/'.ltrim($p,'/');}
 private function call($method,$path,$body=null){$c=$this->cfg();$h=['Accept'=>'application/json','Content-Type'=>'application/json','User-Agent'=>'OMOS-WP/'.self::VERSION];if($c['api_key'])$h['x-omos-key']=$c['api_key'];$a=['method'=>$method,'headers'=>$h,'timeout'=>20];if($body!==null)$a['body']=wp_json_encode($body);$r=wp_remote_request($this->url($path),$a);if(is_wp_error($r))return ['ok'=>false,'status'=>0,'error'=>$r->get_error_message()];$code=wp_remote_retrieve_response_code($r);$raw=wp_remote_retrieve_body($r);$data=json_decode($raw,true);return ['ok'=>$code>=200&&$code<300,'status'=>$code,'data'=>is_array($data)?$data:$raw];}
 private function manifest($force=false){if(!$force&&($v=get_transient(self::CACHE)))return $v;$r=$this->call('GET','api/manifest');if(!$r['ok'])$r=$this->call('GET','manifest');if($r['ok']){set_transient(self::CACHE,$r['data'],max(1,(int)$this->cfg()['cache_minutes'])*MINUTE_IN_SECONDS);return $r['data'];}return [];}
 function heartbeat(){$p=['node'=>home_url('/'),'name'=>$this->cfg()['node_name'],'type'=>$this->cfg()['node_type'],'plugin_version'=>self::VERSION,'wordpress_version'=>get_bloginfo('version'),'php_version'=>PHP_VERSION,'timestamp_utc'=>gmdate('c')];$r=$this->call('POST','api/v1/nodes/heartbeat',$p);update_option('omos_last_heartbeat',['time'=>time(),'response'=>$r],false);return $r;}
 function settings(){register_setting('omos_core_tools',self::OPT,['sanitize_callback'=>function($v){return ['runtime_url'=>esc_url_raw($v['runtime_url']??'https://omos.onegodian.com'),'api_key'=>sanitize_text_field($v['api_key']??''),'cache_minutes'=>max(1,(int)($v['cache_minutes']??5)),'node_name'=>sanitize_text_field($v['node_name']??get_bloginfo('name')),'node_type'=>sanitize_key($v['node_type']??'wordpress')];}]);}
 function menu(){add_menu_page('OMOS','OMOS','manage_options','omos-core',[$this,'admin_dashboard'],'dashicons-networking',3);foreach(['bridge'=>'App Bridge','settings'=>'Settings','keys'=>'API Keys','tools'=>'Tools','status'=>'Status','checklist'=>'Production Checklist','docs'=>'Documentation'] as $s=>$t)add_submenu_page('omos-core',$t,$t,'manage_options','omos-'.$s,[$this,'admin_'.$s]);}
 private function shell($t,$b){echo '<div class="wrap"><h1>'.esc_html($t).'</h1>'.$b.'</div>';}
 function admin_dashboard(){$h=$this->call('GET','api/health');if(!$h['ok'])$h=$this->call('GET','health');$this->shell('OMOS Platform Bridge','<h2>Runtime: '.($h['ok']?'Connected':'Not verified').'</h2><p>'.esc_html($this->url()).'</p><p>Plugin v'.self::VERSION.'</p>');}
 function admin_bridge(){$this->shell('OMOS App Bridge','<p>WordPress is an OMOS interface node. Provider credentials, orchestration, Alignment, Council synthesis and Decision Records remain authoritative in OMOS.</p>');}
 function admin_settings(){$c=$this->cfg();ob_start();?><form method="post" action="options.php"><?php settings_fields('omos_core_tools');?><table class="form-table"><tr><th>Runtime URL</th><td><input class="regular-text" name="<?php echo self::OPT;?>[runtime_url]" value="<?php echo esc_attr($c['runtime_url']);?>"></td></tr><tr><th>Cache minutes</th><td><input type="number" min="1" name="<?php echo self::OPT;?>[cache_minutes]" value="<?php echo esc_attr($c['cache_minutes']);?>"></td></tr><tr><th>Node name</th><td><input class="regular-text" name="<?php echo self::OPT;?>[node_name]" value="<?php echo esc_attr($c['node_name']);?>"></td></tr><tr><th>Node type</th><td><input name="<?php echo self::OPT;?>[node_type]" value="<?php echo esc_attr($c['node_type']);?>"></td></tr></table><?php submit_button();?></form><?php $this->shell('OMOS Settings',ob_get_clean());}
 function admin_keys(){$c=$this->cfg();ob_start();?><p>Store only the OMOS bridge key here. Model-provider keys stay server-side.</p><form method="post" action="options.php"><?php settings_fields('omos_core_tools');foreach(['runtime_url','cache_minutes','node_name','node_type'] as $k)echo '<input type="hidden" name="'.self::OPT.'['.$k.']" value="'.esc_attr($c[$k]).'">';?><input type="password" class="regular-text" name="<?php echo self::OPT;?>[api_key]" value="<?php echo esc_attr($c['api_key']);?>"><?php submit_button('Save Bridge Key');?></form><?php $this->shell('OMOS API Keys',ob_get_clean());}
 function admin_tools(){$this->shell('OMOS Tools',$this->sc_tools([]));}
 function admin_status(){$h=$this->call('GET','api/health');if(!$h['ok'])$h=$this->call('GET','health');$this->shell('OMOS Status','<pre>'.esc_html(wp_json_encode(['health'=>$h,'manifest'=>$this->manifest(true)],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)).'</pre>');}
 function admin_checklist(){$x=['Runtime URL configured'=>!!$this->cfg()['runtime_url'],'Bridge API key configured'=>!!$this->cfg()['api_key'],'HTTPS enabled'=>is_ssl(),'Manifest available'=>!!$this->manifest(),'Heartbeat scheduled'=>!!wp_next_scheduled('omos_hourly_heartbeat')];$b='<ul>';foreach($x as $k=>$v)$b.='<li>'.($v?'✅':'⬜').' '.esc_html($k).'</li>';$this->shell('OMOS Production Checklist',$b.'</ul>');}
 function admin_docs(){$this->shell('OMOS Documentation','<p><a href="https://omos.onegodian.com/docs" target="_blank" rel="noopener">Open OMOS Developer Documentation</a></p><p>REST namespace: <code>/wp-json/omos/v1/</code></p>');}
 function rest(){register_rest_route('omos/v1','/status',['methods'=>'GET','permission_callback'=>'__return_true','callback'=>fn()=>rest_ensure_response(['plugin'=>'OMOS Core Tools','version'=>self::VERSION,'runtime'=>$this->url()])]);register_rest_route('omos/v1','/manifest',['methods'=>'GET','permission_callback'=>'__return_true','callback'=>fn()=>rest_ensure_response($this->manifest())]);register_rest_route('omos/v1','/health',['methods'=>'GET','permission_callback'=>'__return_true','callback'=>function(){$r=$this->call('GET','api/health');if(!$r['ok'])$r=$this->call('GET','health');return rest_ensure_response($r);}]);register_rest_route('omos/v1','/heartbeat',['methods'=>['GET','POST'],'permission_callback'=>fn()=>current_user_can('manage_options'),'callback'=>fn()=>rest_ensure_response($this->heartbeat())]);register_rest_route('omos/v1','/ask',['methods'=>'POST','permission_callback'=>fn()=>is_user_logged_in(),'callback'=>function($req){return rest_ensure_response($this->call('POST','api/v1/council/run',['prompt'=>sanitize_textarea_field($req->get_param('prompt')),'source'=>'wordpress','user_id'=>get_current_user_id(),'node'=>home_url('/')]));}]);}
 private function card($t,$p,$u){return '<a style="display:block;padding:18px;border:1px solid #d8b35a;border-radius:14px;text-decoration:none;margin:8px" href="'.esc_url($u).'"><strong>'.esc_html($t).'</strong><br>'.esc_html($p).'</a>';}
 function sc_status(){ $r=$this->call('GET','api/health');if(!$r['ok'])$r=$this->call('GET','health');return '<div><strong>OMOS Runtime:</strong> '.($r['ok']?'Connected':'Unavailable / not verified').'</div>';}
 function sc_manifest(){return '<pre>'.esc_html(wp_json_encode($this->manifest(),JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)).'</pre>';}
 function sc_ask(){if(!is_user_logged_in())return '<p>Sign in to use Ask OMOS.</p>';return '<p><a href="https://omos.onegodian.com/ask">Open Ask OMOS</a></p>';}
 function sc_council(){return $this->card('OMOS Council','Multi-model governed review','https://omos.onegodian.com/council-of-models');}
 function sc_tools(){return $this->card('Ask OMOS','Governed decision workspace','https://omos.onegodian.com/ask').$this->card('Belief Mapper','Structured belief mapping','https://omos.onegodian.com/belief-mapper').$this->card('Runtime','Health and manifest','https://omos.onegodian.com/dashboard');}
 function sc_docs(){return $this->card('Protocol','Interaction contract','https://omos.onegodian.com/protocol').$this->card('Algorithm','Decision logic','https://omos.onegodian.com/algorithm').$this->card('OHI','Synthesis architecture','https://omos.onegodian.com/ohi');}
 function sc_history(){return '<p><a href="https://omos.onegodian.com/dashboard">Open OMOS Decision History</a></p>';}
 function sc_belief(){return '<p><a href="https://omos.onegodian.com/belief-mapper">Open The Belief Mapper™</a></p>';}
 function sc_dashboard(){return '<h2>OMOS Unity Dashboard</h2>'.$this->sc_status().$this->sc_tools().$this->sc_docs();}
}
register_activation_hook(__FILE__,['OMOS_Core_Tools','activate']);register_deactivation_hook(__FILE__,['OMOS_Core_Tools','deactivate']);new OMOS_Core_Tools();
